# ... lines ommited
on:
  push:
  # ... lines ommited
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/alexa404nl/tec-actions-test
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # ... lines ommited
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GHCR with GITHUB_TOKEN
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  # ... lines ommite
      - name: Build and push (tag=latest)
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ${{ env.IMAGE }}:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max
