# ... lines ommited
on:
push:
# ... lines ommited
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/Alexa404NL/tec-actions-test
jobs:
build:
  runs-on: ubuntu-latest
  steps:
  # ... lines ommited
  - name: Set up Buildx
  uses: docker/setup-buildx-action@v3
  - name: Log in to GHCR
    uses: docker/login-action@v3
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

# ... lines ommited
